#!/bin/bash

if [ "$1" = "-usage" ]; then
    echo "list memo and edit one from the list"
    exit 0
fi

list=$(memo list --format "{{.File}}:{{.Title}}" | column -t -s ":")
greped=$(echo "$list" | grep "$1")
if [ $(echo "$greped" | wc -l) = "1" ]; then
    selected=$greped
else
    selected=$(echo "$list" | peco --query "$1")
fi
test -z "$selected" && exit 0
selected=$(echo "$selected" | cut -d' ' -f1)

memo e "$selected"
